### PR TITLE
Project structure

### PR DESCRIPTION
**Pull request by mich-chmielewski**
Review
I added Maven project structure

### CODE REVIEW

**Comment by isacademyci** [comment]
Build triggered for merge commit.

**Comment by isacademyci** [comment]
Build started for merge commit.

**Comment by isacademyci** [comment]
Build finished.

**Comment by isacademyci** [comment]
Build triggered for merge commit.

**Comment by isacademyci** [comment]
Build started for merge commit.

**Comment by isacademyci** [comment]
Build finished.

**Comment by RobertLegion** [comment]
okok

**Comment by RobertLegion** [comment]
okok

**Pull request merged**
